export default {
  data() {
    return {
      en: {
        //networkMap: {
        family: "Family",
        friends: "Friends",
        colleagues: "Colleagues",
        professionals: "prof. Help",
        maptext: "Click on the map to determine the position",
        //},
        //sideMenu: {
        newNWK: "New NWK",
        open: "Open",
        save: "Save",
        openDemo: "Open demo",
        exportPNG: "Export PNG",
        exportkeyfigures: "Export key figures",
        createPDF: "Create PDF",
        keyfigures: "Key figures",
        abouteasyNWK: "About the easyNWK",
        sourcecode: "Source code (Version 2.0.5)",
        imprint: "Imprint",
        //},
        //statisticPanel: {
        overview: "Overview",
        sector: "Sector",
        profhelp: "prof. help",
        horizon: "Horizon",
        horizoncumulative: "Horizon (cumulative)",
        gender: "Gender",
        networksize: "Network size",
        realtionshipweight: "Relationship weight",
        totaldensity: "Total density",
        stars: "Star(s)",
        bridges: "Bridges",
        bridgepersons: "Bridge person(s)",
        isolatedpersons: "Isolated person(s)",
        personswithoutedgetotheego: "Person(s) without edge to the ego",
        //},
        //viewOptions: {
        viewsettings: "View settings",
        anonymiseon: "Anonymise",
        horizonson: "Horizons on",
        connectionson: "Connections on",
        namesofcontactson: "Name of contacts on",
        ageofcontactson: "Age of contacts on",
        roleofcontactson: "Role of contacts on",
        anonymiseoff: "De-anonymise",
        horizonsoff: "Horizons off",
        connectionsoff: "Connections off",
        namesofcontactsoff: "Name of contacts off",
        ageofcontactsoff: "Age of contacts off",
        roleofcontactsoff: "Role of contacts off",
        //},
        //pdfView: {
        printorpdf: "Print or print as PDF",
        closeandback: "Close & go back to easyNWK",
        printtext:
          "In order to generate a PDF file of this view, select 'Save as PDF' in the print dialogue. You can also highlight the data and copy & paste it into a word processor.",
        //},
        //egoPanel: {},
        //egoEdit: {
        ego: "Ego",
        name: "Name",
        genders: "Gender",
        male: "male",
        female: "female",
        diverse: "diverse",
        notspecified: "not specified",
        age: "Age",
        notesaboutego: "notes about ego",
        Whoisinthecenter: "Who is in the center of the NWK?",
        mandatoryfield: "Mandatory field",
        done: "Done",
        //},
        //alterPanel: {
        contacts: "Contacts",
        nocontactsyet1: "No contacts available yet.",
        nocontactsyet2: "Click on the button with the  ",
        nocontactsyet3: "  symbol to add contacts to the networkmap.",
        //},
        //alterEdit: {
        addcontact: "Add contact",
        positiononmap: "The position on the map still has to be determined.",
        role: "Role",
        human: "Human",
        deceased: "+deceased",
        relationship: "Relationship",
        existing: "existing",
        multiplex: "multiplex",
        nocurrentrelationship: "no current relationship",
        notesaboutcontact: "notes about contact",
        nextcontact: "Next contact",
        close: "Close",
        cancel: "Cancel",
        //},
        //alterConnections: {
        relationshipsof: "Relationships of",
        clickoncontacttoconnect:
          "Click on the contact to connect it/ cancel the connection with",
        possiblecontacts: "Possible contacts",
        connectedcontacts: "Connected contacts",
        //},
      },
    };
  },
};
