export default {
  data() {
    return {
      en: {
        clickMsg1: "Click in the card",
        clickMsg2: "to choose the position",
        relationsMsg1: "Connection to",
        relationsMsg2: "Click on a contact to connect it with ",
        relationsMsg3: "",
        contactsMsg1: "Possible contacts",
        contactsMsg2: "Connected contacts",
        contactsMsg3: "Add contact",
        contactsMsg4: "Edit contact",
        contactsMsg5: "Next contact",
        contactsMsg6: "Contacts",
        contactsMsg7: "No contacts available yet.",
        contactsMsg8: "Click on the button with the",
        contactsMsg9: "symbol to add the contact to the map.",
        contactsMsg10: "Alter relationship to the contact",
        contactsMsg11: "Remove contact",
        doneMsg: "Done",
        positionMsg: "The position has to be selected in the map.",
        nameMsg: "Name",
        nameMsg2: "Name or nickname",
        fieldMsg: "Mandatory field",
        titleMsg1: "Social role of the contact, choices",
        roleMsg: "Role",
        humanMsg: "Human",
        genderMsg1:
          "Biological and/or social gender; categorisation is to be made by the anchor person",
        genderMsg2: "Gender",
        categoryMsg: "Category",
        ageMsg1: "Optional, social age of the contact",
        ageMsg2: "Age",
        deadMsg1: "Select if contact is dead",
        deadMsg2: "dead",
        connectionMsg: "Connection update",
        connectionMsg2: "Connection",
        connectionMsg3:
          "Relationship is currently maintained, updated connection.",
        connectionMsg4: "consists",
        connectionMsg5:
          "Anchor and contact person are connected in several social roles. Relationship fulfills several functions.",
        connectionMsg6: "multiplex",
        connectionMsg7:
          "Anchor person and this person are currently not in contact, relationship is not updated (but ended/broken).",
        connectionMsg8: "currently no relationship",
        notesMsg: "Notes to the contact",
        closeMsg: "Close",
        cancelMsg: "Cancel",
        anchorMsg: "Anchor person",
        anchorMsg2: "Edit anchor person",
        centerMsg: "How is in the center of the NWK?",
        errorMsg: "Something went wrong :-(",
        errorMsg2: "The problem could be solved with the button 'Back'.",
        errorMsg3:
          "With 'Clear cache' you can put easyNWK in the\n" +
          " Reset system status.",
        errorMsg4: "Attention:",
        errorMsg5: "With that, the current data will be lost",
        errorMsg6: "Cache data:",
        errorMsg7: "(can be copied)",
        backMsg: "Back",
        tempMsg: "Delete cache",
      },
    };
  },
};
